---
version: 0.2
env:
  secrets-manager:
    mongo_url: "ADI_MONGO_SECRET:mongodb_url"
phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - echo "MONGODB_URI=$mongo_url" > .env
      - cat .env
      - ls -al
      
  post_build:
    commands:
      - cat app.js
artifacts:
  files:
    - "**/*"
    - echo "Build Artifacts created successfully and uploaded to S3 Bucket"
